options:
  runs-on: self.hosted

definitions:
  steps:
    - step: &unittest-code-checks
        name: test-code-checks
        image:
          name: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
          run-as-user: 1000
        size: 2x
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn run lint --quiet
          - yarn run check-circ-deps
          - yarn run build:prod:ci
          - yarn run test:headless

pipelines:
  branches:
    'main-cris':
      - step: *unittest-code-checks
  pull-requests:
    '**':
      - step: *unittest-code-checks
