options:
  runs-on: self.hosted

definitions:
  caches:
    node-dsc-2023-02-x: ./node_modules
  steps:
    - step: &unittest-code-checks
        name: test-code-checks
        image:
          name: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
          run-as-user: 1000
        size: 4x
        caches:
          - node-dsc-2023-02-x
        script:
          - yarn install --frozen-lockfile
          - yarn run lint --quiet
          - yarn run check-circ-deps
          - yarn run build:prod:ci
          - yarn run test:headless

pipelines:
  branches:
    'dspace-cris-2023_02_x':
      - step: *unittest-code-checks
    'prod/**':
      - step: *unittest-code-checks
  pull-requests:
    '**':
      - step: *unittest-code-checks
