options:
  runs-on: ubuntu-latest

definitions:
  services:
    docker: # can only be used with a self-hosted runner
      image:
        name: cypress/browsers:node18.12.0-chrome107
        run-as-user: 1000
  steps:
    - step: &unittest-code-checks
        name: test-code-checks
        runs-on: self.hosted
        services:
          - docker
        size: 2x
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn run lint --quiet
          - yarn run check-circ-deps
          - yarn run build:prod
          - yarn run test:headless

pipelines:
  branches:
    'dspace-cris-2023_02_x':
      - step: *unittest-code-checks
  pull-requests:
    '**':
      - step: *unittest-code-checks
